// <auto-generated />
using System;
using AutoVenda.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoVenda.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutoVendaDbContext))]
    partial class AutoVendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AutoVenda.Domain.Catalogue.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("TEXT");
                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");
                    b.Property<string>("FipeReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");
                    b.Property<decimal>("PisoDeNegociacao")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");
                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");
                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
